default: &default
  adapter: postgresql
  host: <%= ENV.fetch("DB_HOST") %>
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  min_messages: DEBUG
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lsm_orte_development

test:
  <<: *default
  database: lsm_orte_test

staging:
  <<: *default
  min_messages: WARNING
  database: lsm_orte_staging

production:
  <<: *default
  min_messages: ERROR
  database: lsm_orte_production
