default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: lsm_orte
  password: lsm_orte00
  min_messages: WARNING
  pool: 80

development:
  <<: *default
  database: lsm_orte_development

test:
  <<: *default
  database: lsm_orte_test

staging:
  <<: *default
  database: lsm_orte_staging
  username: lsm_orte
  password: <%%= ENV["LSM_ORTE_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: lsm_orte_production
  username: lsm_orte
  password: <%%= ENV["LSM_ORTE_DATABASE_PASSWORD"] %>
