defaults: &defaults
  app_name: "LSM23 Backend"
  app_shortname: "LSM23"
  app_tagline: "Leerstandsmeldungen"
  app_version: "0.72"
  app_credits: ""
  app_host: "127.0.0.1:3000"
  app_host_protocol: "http"
  app_url: "http://127.0.0.1:3000"
  app_domain: "127.0.0.1"
  github_url: "https://gitlab.com/leerstandsmelder/lsm-orte"
  base_log_level: <%= "#{Logger::DEBUG}" %>
  relative_url_root: ""
  secure: "false"
  default_icon_anchor: ""
  default_icon_size: ""
  default_popup_anchor: ""
  default_class_name: ""

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  app_host: "staging.leerstandsmeldung.de"
  app_host_protocol: "https"
  app_url: "https://staging.leerstandsmeldung.de"
  relative_url_root: ""
  secure: "true"

production:
  <<: *defaults
  app_host: "leerstandsmeldung.de"
  app_host_protocol: "https"
  app_url: "https://leerstandsmeldung.de"
  relative_url_root: ""
  secure: "true"
